version: "3.8"

services:
  nginx:
    build: ./requirements/nginx/.
    image: nginx
    container_name: nginx
    volumes:
      - wordpress-volume:/var/www/html
    ports:
      - "443:443"
    restart: always
    env_file: .env
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress/.
    image: wordpress
    container_name: wp-php
    volumes:
      - wordpress-volume:/var/www/html
    restart: always
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb/.
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb-volume:/var/lib/mysql
    restart: always
    env_file: .env
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: /home/rcortes-/data/wordpress
      o: bind
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      device: /home/rcortes-/data/mariadb
      o: bind

